dateModified: 1618258398
email:
  fromEmail: $BUSINESS_EMAIL
  fromName: $BUSINESS_NAME
  replyToEmail: null
  template: null
  transportSettings:
    apiKey: $MAILGUN_APIKEY
    domain: $MAILGUN_DOMAIN
    endpoint: $MAILGUN_ENDPOINT
  transportType: craft\mailgun\MailgunAdapter
plugins:
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  sidebar-admin-links:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: $BUSINESS_NAME
  retryDuration: null
  schemaVersion: 3.6.7
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
